### ISSUE TITLE
linux Ubuntu 10.04 LTS not working with 1.1.22 and 1.1.21

### ISSUE THREAD

**Issue by SoundBip** [pyfa-org/Pyfa#73]
hello. first of all Thank you very much for this amazing fitting tool.
last version that was working great with my linux computer was 1.1.20
i have the same error message since the traits tab has been implemented

./pyfa.py 
Traceback (most recent call last):
  File "./pyfa.py", line 88, in <module>
    from gui.mainFrame import MainFrame
  File "/home/bip/Bureau/pyfa/new/gui/mainFrame.py", line 39, in <module>
    from gui.additionsPane import AdditionsPane
  File "/home/bip/Bureau/pyfa/new/gui/additionsPane.py", line 22, in <module>
    from gui.boosterView import BoosterView
  File "/home/bip/Bureau/pyfa/new/gui/boosterView.py", line 24, in <module>
    import gui.marketBrowser as mb
  File "/home/bip/Bureau/pyfa/new/gui/marketBrowser.py", line 24, in <module>
    from gui.contextMenu import ContextMenu
  File "/home/bip/Bureau/pyfa/new/gui/contextMenu.py", line 108, in <module>
    from gui.builtinContextMenus import *
  File "/home/bip/Bureau/pyfa/new/gui/builtinContextMenus/itemStats.py", line 2, in <module>
    from gui.itemStats import ItemStatsDialog
  File "/home/bip/Bureau/pyfa/new/gui/itemStats.py", line 29, in <module>
    from collections import OrderedDict
ImportError: cannot import name OrderedDict

thank you for your help and for this amazing tool.
Fly Safe
