### ISSUE TITLE
Project onto active fit not working

### ISSUE THREAD

**Issue by murkar** [pyfa-org/Pyfa#1953]
### Expected behavior:

Project fit from list onto active ship.

### Actual behavior:

Error message.

### Detailed steps to reproduce:

Project any fit from your fittings list onto any other active ship. Fortizar -> Ravens was very problematic for me. 

### Other relevant information:

The error message is as follows:

pyfa v2.9.1
EVE Data Version: 1492195 (2019-04-16 09:50:22)

OS version: Windows-10-10.0.17763-SP0
Python version: 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]
wxPython version: 4.0.4 (wxWidgets 3.0.5)
SQLAlchemy version: 1.0.5
Logbook version: 1.4.3
Requests version: 2.21.0
Dateutil version: 2.8.0

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

####################

Traceback (most recent call last):
  File "C:\projects\pyfa\gui\builtinShipBrowser\fitItem.py", line 188, in OnProjectToFit
AttributeError: module 'gui.fitCommands' has no attribute 'GuiAddProjectedCommand'

**Comment by DarkFenX** [comment]
It's already fixed, will be included in next release, which is going to be done this weekend.

**Comment by DarkFenX** [comment]
Drag-n-drop probably works in 2.9.1, try using it as workaround.
